import { createSlice } from '@reduxjs/toolkit';
import { ordered as cakeOrdered } from '../cake/cakeSlice';

const initialState = {
    numOfIceCream: 10,
};

const icecreamSlice = createSlice({ // auto generate's action creators with same names as reducers function we have written
    name: 'icecream',
    initialState,
    reducers: {
        ordered: (state) => {
            state.numOfIceCream--; // uses immer library under the hood!
        },
        restocked: (state, action) => {
            state.numOfIceCream += action.payload;
        },
    },
    extraReducers: (builder) => {
        builder.addCase(cakeOrdered, (state) => {
            state.numOfIceCream--;
        });
    }
});


export default icecreamSlice.reducer; // autogenerated
export const { ordered, restocked } = icecreamSlice.actions; // autogenerated 