const { cakeActions } = require('../cake/cakeSlice');

const createSlice = require('@reduxjs/toolkit').createSlice

const initialState = {
    numOfIceCream: 10,
};

const icecreamSlice = createSlice({ // auto generate's action creators with same names as reducers function we have written
    name: 'icecream',
    initialState,
    reducers: {
        ordered: (state) => {
            state.numOfIceCream--; // uses immer library under the hood!
        },
        restocked: (state, action) => {
            state.numOfIceCream += action.payload;
        },
    },
    extraReducers: (builder) => {
        builder.addCase(cakeActions.ordered, (state) => {
            state.numOfIceCream--;
        });
    }
});


module.exports = icecreamSlice.reducer; // autogenerated
module.exports.icecreamActions = icecreamSlice.actions; // autogenerated 